version: 1
disable_existing_loggers: true

formatters:
    console:
        format: "[%(asctime)s][%(levelname)s][%(filename)s][%(module)s.%(funcName)s:%(lineno)d] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    file:
        format: "[%(asctime)s][%(levelname)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    network:
        format: "[sampleProject][%(levelname)s] %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout


    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: file
        filename: ./output.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, file_handler]
    propogate: yes
